#!/usr/bin/env bash
# =============================================================================
# Rule File Sync — Generates IDE-specific rule files from .clinerules
# =============================================================================
# .clinerules is the canonical source of truth.
# This script regenerates CLAUDE.md, .cursorrules, .windsurfrules from it.
#
# Usage:
#   bash .ai-operation/scripts/sync-rules.sh
#
# Automatically triggered by git pre-commit hook (see .ai-operation/hooks/)
# =============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

CLINERULES="$PROJECT_ROOT/.clinerules"

if [ ! -f "$CLINERULES" ]; then
    echo "[sync-rules] ERROR: .clinerules not found at $CLINERULES"
    exit 1
fi

RULES_BODY=$(cat "$CLINERULES")

# ── Generate CLAUDE.md ───────────────────────────────────────────────────────
cat > "$PROJECT_ROOT/CLAUDE.md" << CLAUDE_EOF
# AI-Operation Framework Rules (Claude Code)

> This file is auto-generated from \`.clinerules\` (the canonical source).
> Do NOT edit this file directly. Edit \`.clinerules\` and run:
> \`bash .ai-operation/scripts/sync-rules.sh\`
> MCP tools are configured in \`.mcp.json\` at the project root.

---

$RULES_BODY
CLAUDE_EOF

# ── Generate .cursorrules ────────────────────────────────────────────────────
cat > "$PROJECT_ROOT/.cursorrules" << CURSOR_EOF
// AI-Operation Framework Rules (Cursor)
// This file is auto-generated from .clinerules (the canonical source).
// Do NOT edit this file directly. Edit .clinerules and run:
//   bash .ai-operation/scripts/sync-rules.sh
// MCP tools are configured in .cursor/mcp.json.

$RULES_BODY
CURSOR_EOF

# ── Generate .windsurfrules ──────────────────────────────────────────────────
cat > "$PROJECT_ROOT/.windsurfrules" << WINDSURF_EOF
// AI-Operation Framework Rules (Windsurf)
// This file is auto-generated from .clinerules (the canonical source).
// Do NOT edit this file directly. Edit .clinerules and run:
//   bash .ai-operation/scripts/sync-rules.sh
// MCP tools are configured in .windsurf/mcp.json.

$RULES_BODY
WINDSURF_EOF

echo "[sync-rules] Synced .clinerules → CLAUDE.md, .cursorrules, .windsurfrules"
