# =============================================================================
# Rule File Sync — Generates IDE-specific rule files from .clinerules
# =============================================================================
# .clinerules is the canonical source of truth.
# This script regenerates CLAUDE.md, .cursorrules, .windsurfrules from it.
#
# Usage:
#   powershell .ai-operation\scripts\sync-rules.ps1
# =============================================================================

$ErrorActionPreference = "Stop"

$ProjectRoot = Split-Path (Split-Path $PSScriptRoot -Parent) -Parent
$ClinerulesPath = Join-Path $ProjectRoot ".clinerules"

if (-not (Test-Path $ClinerulesPath)) {
    Write-Host "[sync-rules] ERROR: .clinerules not found at $ClinerulesPath" -ForegroundColor Red
    exit 1
}

$RulesBody = Get-Content $ClinerulesPath -Raw

# -- Generate CLAUDE.md --
$claudeContent = @"
# AI-Operation Framework Rules (Claude Code)

> This file is auto-generated from ``.clinerules`` (the canonical source).
> Do NOT edit this file directly. Edit ``.clinerules`` and run:
> ``powershell .ai-operation\scripts\sync-rules.ps1``
> MCP tools are configured in ``.mcp.json`` at the project root.

---

$RulesBody
"@
Set-Content (Join-Path $ProjectRoot "CLAUDE.md") $claudeContent -NoNewline

# -- Generate .cursorrules --
$cursorContent = @"
// AI-Operation Framework Rules (Cursor)
// This file is auto-generated from .clinerules (the canonical source).
// Do NOT edit this file directly. Edit .clinerules and run:
//   powershell .ai-operation\scripts\sync-rules.ps1
// MCP tools are configured in .cursor/mcp.json.

$RulesBody
"@
Set-Content (Join-Path $ProjectRoot ".cursorrules") $cursorContent -NoNewline

# -- Generate .windsurfrules --
$windsurfContent = @"
// AI-Operation Framework Rules (Windsurf)
// This file is auto-generated from .clinerules (the canonical source).
// Do NOT edit this file directly. Edit .clinerules and run:
//   powershell .ai-operation\scripts\sync-rules.ps1
// MCP tools are configured in .windsurf/mcp.json.

$RulesBody
"@
Set-Content (Join-Path $ProjectRoot ".windsurfrules") $windsurfContent -NoNewline

Write-Host "[sync-rules] Synced .clinerules -> CLAUDE.md, .cursorrules, .windsurfrules" -ForegroundColor Green
