"""
Cognitive Gate -- forces AI to read project context before any file operation.

Contains: aio__confirm_read, aio__load_experience

Key-Value File Pattern:
  corrections.md = keys only (fileops, git, save, analysis...)
  corrections/*.md = values (actual experience details)
  AI sees keys on boot, loads values on demand via aio__load_experience.
  This minimizes context consumption while ensuring relevant experience
  is loaded precisely when needed.

Flow:
  1. [存档] writes a random SESSION_KEY to corrections.md
  2. New session: AI reads corrections.md, sees keys + SESSION_KEY
  3. AI calls aio__confirm_read(session_key=xxx)
  4. Tool verifies key matches -> writes .session_confirmed (with counter=0)
  5. AI about to do file ops -> calls aio__load_experience(key="fileops")
  6. Tool returns experience content from corrections/fileops.md
  7. Hook checks .session_confirmed exists + counter < 30 -> allows tool use
"""

from pathlib import Path
from mcp.server.fastmcp import FastMCP
from .constants import *


SESSION_CONFIRMED_FLAG = Path(".ai-operation/.session_confirmed")
SAVE_PENDING_FLAG = Path(".ai-operation/.save_pending")


SAVE_PENDING_TTL_SECONDS = 1800  # 30 minutes


def is_save_pending() -> bool:
    """Check if a save is already pending confirmation. Auto-clears after 30 min."""
    if not SAVE_PENDING_FLAG.exists():
        return False
    import time
    age = time.time() - SAVE_PENDING_FLAG.stat().st_mtime
    if age > SAVE_PENDING_TTL_SECONDS:
        SAVE_PENDING_FLAG.unlink()
        return False
    return True


def set_save_pending():
    """Mark that a save is pending confirmation."""
    SAVE_PENDING_FLAG.parent.mkdir(parents=True, exist_ok=True)
    SAVE_PENDING_FLAG.write_text("pending", encoding="utf-8")


def clear_save_pending():
    """Clear the save-pending flag."""
    if SAVE_PENDING_FLAG.exists():
        SAVE_PENDING_FLAG.unlink()


def register_cognitive_gate_tools(mcp: FastMCP, _audit, _loop_guard):
    """Register cognitive gate tools."""

    @mcp.tool()
    def aio__confirm_read(session_key: str) -> str:
        """
        [COGNITIVE GATE] Confirm that you have read corrections.md and conventions.md.

        You MUST call this tool at the start of every session, BEFORE making any
        file changes. Without this, all Edit/Write/Bash tools will be BLOCKED.

        How to get the session_key:
        1. Read .ai-operation/docs/project_map/corrections.md
        2. Find the SESSION_KEY line at the bottom
        3. Pass that value here

        This tool also resets the operation counter. After 30 file operations,
        you must re-read corrections.md and call this again.

        Args:
            session_key: The SESSION_KEY value from corrections.md
        """
        _audit("aio__confirm_read", "CALLED", session_key[:20] if session_key else "")

        # Read the actual key from corrections.md
        corrections_path = PROJECT_MAP_DIR / "corrections.md"
        if not corrections_path.exists():
            _audit("aio__confirm_read", "REJECTED", "corrections.md not found")
            return (
                "REJECTED: corrections.md not found.\n"
                "Run [初始化项目] first."
            )

        content = corrections_path.read_text(encoding="utf-8")

        # Extract SESSION_KEY from file
        actual_key = None
        for line in content.split("\n"):
            if line.startswith("SESSION_KEY:"):
                actual_key = line.split(":", 1)[1].strip()
                break

        if not actual_key:
            # No key in file -- framework not fully initialized.
            # SESSION_KEY is set by aio__force_architect_save_confirm or bootstrap.
            _audit("aio__confirm_read", "REJECTED", "no SESSION_KEY in corrections.md")
            return (
                "REJECTED: corrections.md has no SESSION_KEY.\n"
                "Run [初始化项目] or [存档] first to initialize the session key.\n"
                "SESSION_KEY is generated by the framework, not by this tool."
            )

        if session_key.strip() != actual_key:
            _audit("aio__confirm_read", "REJECTED", f"key mismatch: got={session_key[:10]} expected={actual_key[:10]}")
            return (
                f"REJECTED: session_key does not match.\n"
                f"Re-read corrections.md and find the current SESSION_KEY value.\n"
                f"You may have read an outdated version."
            )

        # Write confirmed flag with counter=0
        SESSION_CONFIRMED_FLAG.parent.mkdir(parents=True, exist_ok=True)
        SESSION_CONFIRMED_FLAG.write_text("0", encoding="utf-8")

        # Read available keys from corrections.md to show AI what's available
        import time as _time
        corrections_dir = PROJECT_MAP_DIR.parent / "corrections"
        keys = []
        keys_display = []
        for line in content.split("\n"):
            line = line.strip()
            if line.startswith("- ") and not line.startswith("- ["):
                key_name = line[2:].split("SINCE:")[0].strip()
                keys.append(key_name)
                # Show freshness per key
                key_file = corrections_dir / f"{key_name}.md"
                if key_file.exists():
                    age_days = int((_time.time() - key_file.stat().st_mtime) / 86400)
                    stale_mark = " [!]STALE" if age_days > 30 else ""
                    keys_display.append(f"  - {key_name} ({age_days}d ago{stale_mark})")
                else:
                    keys_display.append(f"  - {key_name} (no file)")

        _audit("aio__confirm_read", "SUCCESS", f"key={actual_key},experience_keys={','.join(keys)}")

        keys_list = "\n".join(keys_display) if keys_display else "  (none)"
        return (
            "SUCCESS: Context confirmed. You may now use Edit/Write/Bash tools.\n"
            "After 30 file operations, you will need to re-read and re-confirm.\n\n"
            f"Available experience keys (call aio__load_experience before related work):\n{keys_list}"
        )

    @mcp.tool()
    def aio__load_experience(key: str) -> str:
        """
        [COGNITIVE GATE] Load project-specific experience by key.

        Before doing work related to a specific area, call this tool to load
        the relevant experience/lessons. Keys are listed in corrections.md.

        Example keys: fileops, git, save, api, naming, deploy
        The key maps to a file in .ai-operation/docs/corrections/{key}.md

        Args:
            key: The experience category key from corrections.md
        """
        _audit("aio__load_experience", "CALLED", key)

        corrections_dir = PROJECT_MAP_DIR.parent / "corrections"
        experience_file = corrections_dir / f"{key}.md"

        if not experience_file.exists():
            # List available keys
            available = []
            if corrections_dir.exists():
                available = [f.stem for f in corrections_dir.glob("*.md")]
            _audit("aio__load_experience", "NOT_FOUND", f"key={key}")
            return (
                f"No experience found for key '{key}'.\n"
                f"Available keys: {', '.join(available) if available else '(none)'}\n"
                f"To add new experience, create .ai-operation/docs/corrections/{key}.md during [整理]."
            )

        content = experience_file.read_text(encoding="utf-8")

        # Freshness tracking: warn if experience file is stale
        import time
        mtime = experience_file.stat().st_mtime
        age_days = int((time.time() - mtime) / 86400)
        freshness = ""
        if age_days > 30:
            freshness = (
                f"\n\n[!] STALE ({age_days} days since last update). "
                f"Verify these lessons still apply before relying on them."
            )
        elif age_days > 7:
            freshness = f"\n\n(Last updated {age_days} days ago)"

        _audit("aio__load_experience", "SUCCESS", f"key={key}, size={len(content)}, age={age_days}d")
        return _budget_truncate(content + freshness)
